import { describe, expect, it } from "vitest";
import { z } from "zod";

import { assertAllKeysPresent, resolveMessages } from "../src/i18n/catalog.js";
import {
  RendererError,
  RendererErrorCode,
  createPluginRegistry,
  render,
} from "../src/renderer.js";
import type { ArtifactKindPlugin, RenderContext } from "../src/renderer.js";

const ctx: RenderContext = {
  audience: "student",
  locale: "vi",
  theme: "default",
  renderMode: "preview",
  requestId: "i18n-test",
  versions: { rendererVersion: "test-v1" },
  assetPolicy: "inline-only",
};

const quizInput = {
  title: "T",
  subject: "S",
  gradeLevel: "G",
  timeLimit: 5,
  questions: [{ id: "q1", prompt: "P?", options: [{ label: "A", text: "opt-a" }], answer: "A" }],
};

const lessonInput = {
  title: "T",
  subject: "S",
  gradeLevel: "G",
  objectives: [],
  sections: [{ heading: "S1", body: "body text" }],
};

const tinySchema = z.object({ title: z.string().min(1) });

type TinyTemplateData = {
  readonly title: string;
  readonly body: string;
  readonly lang: string;
  readonly type: string;
  readonly themeCSS: string;
};

const tinyPlugin: ArtifactKindPlugin<TinyTemplateData> = {
  kind: "test.tiny",
  version: "tiny-v1",
  templateVersion: "base-v1",
  themeVersion: "theme-v1",
  schema: tinySchema,
  audience: { supported: ["teacher"] },
  capabilities: { supportsPrint: false },
  sanitizerPolicy: { version: "sanitizer-v1" },
  adapt: (input, renderContext, services) => {
    const tinyInput = tinySchema.parse(input);
    return {
      title: tinyInput.title,
      body: `<section><p>${tinyInput.title}</p><p>${renderContext.requestId}</p></section>`,
      lang: renderContext.locale,
      type: "tiny",
      themeCSS: services.themeCss,
    };
  },
  templatePath: () => "base",
};

describe("i18n catalog", () => {
  it("resolves Vietnamese messages for all keys", () => {
    const messages = resolveMessages("vi");
    assertAllKeysPresent(messages);
    expect(messages["label.generatedBy"]).toBe("Được tạo bởi oh-my-class");
    expect(messages["label.quiz.explanation"]).toBe("Giải thích");
  });

  it("resolves English messages for all keys", () => {
    const messages = resolveMessages("en");
    assertAllKeysPresent(messages);
    expect(messages["label.generatedBy"]).toBe("Generated by oh-my-class");
    expect(messages["label.quiz.explanation"]).toBe("Explanation");
  });

  it("resolveMessages returns different catalogs for vi vs en", () => {
    expect(resolveMessages("vi")).not.toBe(resolveMessages("en"));
  });
});

describe("print mode validation", () => {
  it("throws UnsupportedMode when plugin does not support print", async () => {
    const registry = createPluginRegistry([tinyPlugin]);
    await expect(
      render(
        { kind: "test.tiny", input: { title: "T" }, context: { ...ctx, audience: "teacher", renderMode: "print" } },
        { registry },
      ),
    ).rejects.toSatisfy((error: unknown) => {
      expect(error).toBeInstanceOf(RendererError);
      if (error instanceof RendererError) {
        expect(error.code).toBe(RendererErrorCode.UnsupportedMode);
      }
      return true;
    });
  });

  it("renders quiz in print mode", async () => {
    const response = await render({ kind: "quiz", input: quizInput, context: { ...ctx, renderMode: "print" } });
    expect(response.html).toMatch(/^<!DOCTYPE html>/);
  });

  it("renders lesson in print mode", async () => {
    const response = await render({ kind: "lesson", input: lessonInput, context: { ...ctx, renderMode: "print" } });
    expect(response.html).toMatch(/^<!DOCTYPE html>/);
  });
});

describe("visual/print smoke", () => {
  it("renders quiz for student (preview)", async () => {
    const response = await render({ kind: "quiz", input: quizInput, context: ctx });
    expect(response.html).toMatch(/^<!DOCTYPE html>/);
    expect(response.html).not.toMatch(/https?:\/\//);
    expect(response.html).toContain("P?");
  });

  it("renders lesson for student (preview)", async () => {
    const response = await render({ kind: "lesson", input: lessonInput, context: ctx });
    expect(response.html).toMatch(/^<!DOCTYPE html>/);
    expect(response.html).not.toMatch(/https?:\/\//);
    expect(response.html).toContain("T");
  });

  it("renders lesson for student (print)", async () => {
    const response = await render({ kind: "lesson", input: lessonInput, context: { ...ctx, renderMode: "print" } });
    expect(response.html).toMatch(/^<!DOCTYPE html>/);
  });

  it("manifest includes locale, renderMode, audience, requestId", async () => {
    const response = await render({ kind: "quiz", input: quizInput, context: ctx });
    expect(response.manifest.locale).toBe("vi");
    expect(response.manifest.renderMode).toBe("preview");
    expect(response.manifest.audience).toBe("student");
    expect(response.manifest.requestId).toBe("i18n-test");
  });
});
