import { describe, expect, it } from "vitest";

import { renderArtifact } from "../src/renderer.js";
import type { ArtifactDataMap, SlideDeckData } from "../src/contracts/index.js";

// SDH-02 (ADR-043): full 5-surface set + chrome policy. This suite targets
// the exact leak vectors named in the SDH-02 acceptance criteria (data
// attributes, inline JSON/script, hidden elements, HTML comments) and the
// surface+chrome-driven "Generated by oh-my-class" provenance policy.
// It builds on `slide-deck-renderer.test.ts` (basic student/teacher/print
// safety) and `slide-deck-display-preferences.test.ts` (preference
// resolution) rather than re-testing those.

const LEAK_FACILITATION_NOTE = 'LEAK_FACILITATION data-answer="42" <!-- LEAK_COMMENT --> <script>JSON.parse("LEAK_JSON")</script> <div style="display:none">LEAK_HIDDEN</div>';
const LEAK_ANSWER_KEY_NOTE = "LEAK_ANSWER_KEY_NOTE";
const LEAK_RATIONALE = 'LEAK_RATIONALE data-correct="b" <script>JSON.parse("LEAK_RATIONALE_JSON")</script>';
const LEAK_ACCEPTABLE_ANSWER = "LEAK_ACCEPTABLE_ANSWER";

const deck: SlideDeckData = {
  deck_id: "deck-surface-chrome-test",
  title: "Surface and Chrome Policy Deck",
  locale: "en-US",
  theme: "default",
  surfaces: {
    student: { mode: "presentation", export_format: "html" },
    teacher: { mode: "teacher_guide", export_format: "html" },
    print: { mode: "print", export_format: "html" },
  },
  slides: [
    {
      slide_id: "slide-1",
      title: "Leak Vector Slide",
      layout: "question",
      progression: { step_index: 1, reveal_policy: "all_at_once" },
      blocks: [
        { block_id: "block-1", block_type: "heading", body: "Leak Vector Slide" },
      ],
      teacher_notes: {
        facilitation_notes: [LEAK_FACILITATION_NOTE],
        answer_key_notes: [LEAK_ANSWER_KEY_NOTE],
      },
      interactions: [
        {
          interaction_id: "interaction-1",
          interaction_type: "multiple_choice_single",
          prompt: "Which one?",
          answer_bearing: true,
          options: [
            { option_id: "a", label: "Option A" },
            { option_id: "b", label: "Option B" },
          ],
          teacher_only: {
            separation: "teacher_only_projection",
            correct_option_ids: ["b"],
            acceptable_answers: [LEAK_ACCEPTABLE_ANSWER],
            rationale: LEAK_RATIONALE,
          },
        },
      ],
    },
  ],
  accessibility: {
    reading_level: "Grade 5",
    language: "en",
    alt_text_required: true,
    keyboard_navigation: true,
  },
  media_policy: {
    default_tier: "packaged",
    online_optional_allowed: false,
    fallback_required: false,
  },
};

const ALL_LEAK_MARKERS = [
  "LEAK_FACILITATION",
  "LEAK_COMMENT",
  "LEAK_JSON",
  "LEAK_HIDDEN",
  "data-answer",
  LEAK_ANSWER_KEY_NOTE,
  "LEAK_RATIONALE",
  "data-correct",
  LEAK_ACCEPTABLE_ANSWER,
];

describe("slide_deck surface recognition (ADR-043)", () => {
  it.each(["presentation", "student", "teacher", "print", "review"] as const)(
    "renders the %s surface without throwing",
    async (surface) => {
      const html = await renderArtifact("slide_deck", { ...deck, render_surface: surface });
      expect(html).toContain("<!DOCTYPE html>");
    },
  );

  it("maps an unrecognized/legacy render_surface value to the safest default instead of throwing", async () => {
    const html = await renderArtifact("slide_deck", {
      ...deck,
      // Untyped at the Python/TS JSON boundary -- cast to bypass the TS
      // union so this exercises the runtime fallback in
      // `normalizeRenderSurface`, not a compile-time guarantee.
      render_surface: "not_a_real_surface" as SlideDeckData["render_surface"],
    });
    // Falls back to "student": clean chrome, no navigation-toolbar leak of
    // an unrecognized surface label, and definitely no teacher-only data.
    expect(html).toContain('data-surface="student"');
    for (const marker of ALL_LEAK_MARKERS) expect(html).not.toContain(marker);
  });
});

describe("slide_deck teacher-only leak vectors are absent from student/presentation HTML (SDH-02)", () => {
  it.each(["student", "presentation"] as const)(
    "excludes every leak vector from %s HTML: data attributes, inline JSON/script, hidden elements, comments",
    async (surface) => {
      const html = await renderArtifact("slide_deck", { ...deck, render_surface: surface });

      for (const marker of ALL_LEAK_MARKERS) {
        expect(html).not.toContain(marker);
      }
      // Not just absent as bare text -- also confirm the structural forms
      // named in the AC never appear, i.e. safety isn't achieved by
      // rendering-then-hiding-with-CSS.
      expect(html).not.toMatch(/data-answer/);
      expect(html).not.toMatch(/data-correct/);
      expect(html).not.toMatch(/<!--[^>]*LEAK/);
      expect(html).not.toMatch(/<script[^>]*>[^<]*LEAK/);
      expect(html).not.toMatch(/display:\s*none[^>]*>[^<]*LEAK/);
      expect(html).not.toContain("Correct</strong>");
    },
  );

  it("keeps print's safe projection guarded the same way (no forbiddenStudentText gap)", async () => {
    const html = await renderArtifact("slide_deck", { ...deck, render_surface: "print" });
    for (const marker of ALL_LEAK_MARKERS) expect(html).not.toContain(marker);
  });

  it.each(["teacher", "review"] as const)(
    "surfaces full teacher-only content on the %s surface (not a student-facing view)",
    async (surface) => {
      const html = await renderArtifact("slide_deck", { ...deck, render_surface: surface });
      expect(html).toContain("LEAK_FACILITATION");
      expect(html).toContain(LEAK_ANSWER_KEY_NOTE);
      expect(html).toContain("LEAK_RATIONALE");
      expect(html).toContain("Correct</strong>");
    },
  );

  it("fails closed if a presentation-surface projection somehow carried teacher-only text", async () => {
    const unsafeDeck: SlideDeckData = {
      ...deck,
      slides: [
        {
          ...deck.slides[0],
          blocks: [
            ...deck.slides[0].blocks,
            { block_id: "leaky-block", block_type: "paragraph", body: LEAK_ANSWER_KEY_NOTE },
          ],
        },
      ],
    };

    await expect(
      renderArtifact("slide_deck", { ...unsafeDeck, render_surface: "presentation" }),
    ).rejects.toThrow("Student slide deck HTML leaked teacher-only data");
  });
});

describe("slide_deck chrome/provenance policy follows surface + preference (ADR-043 decision 6)", () => {
  it.each(["student", "presentation"] as const)(
    "%s never shows 'Generated by oh-my-class' chrome, even if chrome:branded is requested",
    async (surface) => {
      const html = await renderArtifact("slide_deck", {
        ...deck,
        render_surface: surface,
        display_preferences: { chrome: "branded" },
      });
      expect(html).not.toContain("Generated by oh-my-class");
      expect(html).not.toContain('<span class="brand">oh-my-class</span>');
    },
  );

  it("print hides the footer by default (chrome defaults to hidden)", async () => {
    const html = await renderArtifact("slide_deck", { ...deck, render_surface: "print" });
    expect(html).not.toContain("Generated by oh-my-class");
  });

  it.each(["minimal", "branded"] as const)(
    "print shows the footer once the teacher opts in via chrome:%s",
    async (chrome) => {
      const html = await renderArtifact("slide_deck", {
        ...deck,
        render_surface: "print",
        display_preferences: { chrome },
      });
      expect(html).toContain("Generated by oh-my-class");
    },
  );

  it.each(["teacher", "review"] as const)(
    "%s always shows provenance regardless of chrome preference",
    async (surface) => {
      const html = await renderArtifact("slide_deck", {
        ...deck,
        render_surface: surface,
        display_preferences: { chrome: "hidden" },
      });
      expect(html).toContain("Generated by oh-my-class");
    },
  );

  it("other artifact types are unaffected by the slide_deck-only chrome policy", async () => {
    const quizData: ArtifactDataMap["quiz"] = {
      title: "Unrelated quiz",
      subject: "Math",
      gradeLevel: "Grade 5",
      questions: [{ id: "q1", prompt: "2+2?", options: [{ label: "A", text: "3" }, { label: "B", text: "4" }], answer: "B" }],
    };
    const html = await renderArtifact("quiz", quizData);
    expect(html).toContain("Generated by oh-my-class");
  });
});
