export type InverseThinkingArtifactKind = "lesson" | "worksheet" | "quiz" | "drill" | "teacher_only";
export type InverseThinkingFrame = "detective_case" | "neutral";

export interface InverseThinkingRenderCase {
  readonly id: string;
  readonly title: string;
  readonly alias?: string | null;
  readonly disaster: string;
  readonly key_clues: readonly string[];
  readonly safe_zone: string;
  readonly filing_note: string;
  readonly student_task: string;
  readonly teacher_only: {
    readonly rationale: string;
    readonly answer_key: string;
  };
}

export interface InverseThinkingSummaryRow {
  readonly case_id: string;
  readonly trap: string;
  readonly clue: string;
  readonly safe_rule: string;
}

export interface InverseThinkingRenderInput {
  readonly artifactType: InverseThinkingArtifactKind;
  readonly title: string;
  readonly subject: string;
  readonly gradeLevel: string;
  readonly frame: InverseThinkingFrame;
  readonly lang?: string;
  readonly cases: readonly InverseThinkingRenderCase[];
  readonly summaryTable: readonly InverseThinkingSummaryRow[];
  readonly teacherOnly: {
    readonly rationale: string;
    readonly answer_key: string;
  };
}

export function renderInverseThinkingHtml(input: InverseThinkingRenderInput): string {
  const frameClass = input.frame === "detective_case" ? "frame-detective" : "frame-neutral";
  const isTeacherOnly = input.artifactType === "teacher_only";
  const html = `<!DOCTYPE html>
<html lang="${escapeHtml(input.lang ?? "vi")}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(input.title)} — oh-my-class</title>
  <style>${styles()}</style>
</head>
<body class="inverse-thinking ${frameClass}">
  <header class="it-header">
    <span class="brand">oh-my-class</span>
    <span>${escapeHtml(input.subject)} · ${escapeHtml(input.gradeLevel)}</span>
  </header>
  <main class="it-shell">
    <section class="it-hero">
      <p class="it-eyebrow">${isTeacherOnly ? "Teacher key" : labelFor(input.artifactType)}</p>
      <h1>${escapeHtml(input.title)}</h1>
      <p>Disaster-first thinking: inspect the scene, collect clues, enter the safe zone, then file the learning note.</p>
    </section>
    ${isTeacherOnly ? teacherOnlyHtml(input) : studentHtml(input)}
  </main>
  <footer class="it-footer">Generated by oh-my-class</footer>
</body>
</html>`;
  return html;
}

function assertNever(value: never): never {
  throw new Error(`Unhandled inverse-thinking artifact kind: ${String(value)}`);
}

function studentHtml(input: InverseThinkingRenderInput): string {
  return `${input.cases.map(caseHtml).join("\n")}${summaryHtml(input.summaryTable)}${challengeHtml(input)}`;
}

function caseHtml(item: InverseThinkingRenderCase): string {
  return `<article class="case-file page-break" data-case-id="${escapeHtml(item.id)}">
    <div class="case-title"><span>${escapeHtml(item.alias ?? item.id)}</span><h2>${escapeHtml(item.title)}</h2></div>
    <section class="evidence-card"><h3>Scene</h3><p>${escapeHtml(item.disaster)}</p></section>
    <section class="clue-chip-row"><h3>Key clues</h3>${item.key_clues.map((clue) => `<span class="clue-chip">${escapeHtml(clue)}</span>`).join("")}</section>
    <section class="safe-zone"><h3>Safe zone</h3><p>${escapeHtml(item.safe_zone)}</p></section>
    <section class="filing-note"><h3>Filing note</h3><p>${escapeHtml(item.filing_note)}</p></section>
    <section class="student-challenge"><h3>Challenge</h3><p>${escapeHtml(item.student_task)}</p></section>
  </article>`;
}

function summaryHtml(rows: readonly InverseThinkingSummaryRow[]): string {
  return `<section class="summary-wrap"><h2>Summary table</h2><div class="table-scroll"><table><thead><tr><th>Case</th><th>Trap</th><th>Clue</th><th>Safe rule</th></tr></thead><tbody>${rows.map((row) => `<tr><td>${escapeHtml(row.case_id)}</td><td>${escapeHtml(row.trap)}</td><td>${escapeHtml(row.clue)}</td><td>${escapeHtml(row.safe_rule)}</td></tr>`).join("")}</tbody></table></div></section>`;
}

function challengeHtml(input: InverseThinkingRenderInput): string {
  if (input.artifactType === "lesson") {
    return "";
  }
  return `<section class="student-practice"><h2>${labelFor(input.artifactType)} practice</h2><p>Use the same case-file steps on the next unsafe example.</p></section>`;
}

function teacherOnlyHtml(input: InverseThinkingRenderInput): string {
  return `<section class="teacher-only"><h2>Teacher-only rationale</h2><p>${escapeHtml(input.teacherOnly.rationale)}</p><h2>Answer key</h2><p>${escapeHtml(input.teacherOnly.answer_key)}</p>${input.cases.map((item) => `<article class="teacher-case"><h3>${escapeHtml(item.id)}</h3><p>${escapeHtml(item.teacher_only.rationale)}</p><p>${escapeHtml(item.teacher_only.answer_key)}</p></article>`).join("")}</section>`;
}

function labelFor(kind: InverseThinkingArtifactKind): string {
  switch (kind) {
    case "lesson":
      return "Case-file lesson";
    case "worksheet":
      return "Evidence worksheet";
    case "quiz":
      return "Clue quiz";
    case "drill":
      return "Repair drill";
    case "teacher_only":
      return "Teacher key";
    default:
      return assertNever(kind);
  }
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function styles(): string {
  return `:root{color-scheme:light;--paper:#fffaf0;--ink:#1f2937;--muted:#6b7280;--line:#d7c9aa;--accent:#7c2d12;--safe:#166534;--clue:#1d4ed8}*{box-sizing:border-box}body{margin:0;font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;background:#f8f4e8;color:var(--ink);line-height:1.55}.frame-neutral{--paper:#ffffff;--line:#d1d5db;--accent:#374151;--safe:#166534;--clue:#1d4ed8}.it-header,.it-footer{display:flex;justify-content:space-between;gap:1rem;padding:1rem clamp(1rem,4vw,3rem);color:var(--muted)}.brand{font-weight:800;color:var(--accent)}.it-shell{width:min(1120px,100%);margin:0 auto;padding:0 clamp(1rem,4vw,3rem) 3rem}.it-hero,.case-file,.summary-wrap,.student-practice,.teacher-only{background:var(--paper);border:1px solid var(--line);border-radius:24px;box-shadow:0 18px 45px rgba(31,41,55,.08);margin:1rem 0;padding:clamp(1rem,3vw,2rem)}.it-eyebrow{text-transform:uppercase;letter-spacing:.16em;color:var(--accent);font-weight:800}.case-title{display:flex;align-items:center;gap:1rem;flex-wrap:wrap}.case-title span,.clue-chip{display:inline-flex;border:1px solid var(--line);border-radius:999px;padding:.35rem .7rem;background:#fff}.evidence-card{border-left:6px solid var(--accent);padding-left:1rem}.clue-chip-row{display:flex;gap:.6rem;flex-wrap:wrap}.clue-chip{color:var(--clue);font-weight:700}.safe-zone{border-left:6px solid var(--safe);padding-left:1rem}.filing-note{border-top:1px dashed var(--line);padding-top:1rem}.table-scroll{overflow-x:auto}table{border-collapse:collapse;width:100%;min-width:680px}th,td{border:1px solid var(--line);padding:.75rem;text-align:left;vertical-align:top}th{background:rgba(124,45,18,.08)}@media(max-width:480px){.it-header{flex-direction:column}.case-file,.summary-wrap{border-radius:16px}.case-title{align-items:flex-start}}@media print{body{background:#fff}.it-header,.it-footer{display:none}.case-file,.summary-wrap,.student-practice,.teacher-only{box-shadow:none;break-inside:avoid}.page-break{page-break-inside:avoid}}`;
}
