/**
 * Core renderer — takes ArtifactContent JSON and produces standalone HTML.
 * All output is self-contained: theme CSS inlined, no CDN, no external assets.
 */

import { Eta } from "eta";
import type { ArtifactContent } from "@oh-my-class/schemas";
import { sanitizeHtml } from "./sanitizer.js";

const eta = new Eta({ views: "./templates" });

const TEMPLATE_MAP: Record<string, string> = {
	lesson: "pages/lesson",
	worksheet: "pages/worksheet",
	quiz: "pages/quiz",
	drill: "pages/drill",
	recap: "pages/recap",
	infographic: "pages/infographic",
};

const themeCache: Map<string, string> = new Map();

function loadThemeCss(theme: string): string {
	if (themeCache.has(theme)) return themeCache.get(theme)!;
	// Minimal inline theme CSS — production path reads generated theme_*.css
	const css = `
    :root {
        --color-primary: #3b82f6;
        --font-family: system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif;
        --font-size-base: 16px;
        --color-text: #1e293b;
        --color-background: #ffffff;
    }
    body {
        font-family: var(--font-family);
        font-size: var(--font-size-base);
        color: var(--color-text);
        background-color: var(--color-background);
        margin: 0;
        padding: 1rem;
    }`.trim();
	themeCache.set(theme, css);
	return css;
}

function buildContentHtml(data: ArtifactContent): string {
	const sections = data.sections ?? [];
	const sectionsHtml = sections
		.map((s) => {
			const title =
				typeof s["title"] === "string"
					? `<h2>${s["title"]}</h2>`
					: "";
			const content =
				typeof s["content"] === "string"
					? `<p>${s["content"]}</p>`
					: "";
			return `    <section>${title}${content}</section>`;
		})
		.join("\n");
	return `    <h1>${data.title}</h1>\n${sectionsHtml}`;
}

/**
 * Render ArtifactContent to a sanitized, standalone HTML string.
 */
export function renderArtifact(data: ArtifactContent): string {
	const templateKey = data.artifact_type;
	if (!TEMPLATE_MAP[templateKey]) {
		throw new Error(`Unknown artifact type: ${data.artifact_type}`);
	}

	const theme = data.theme ?? "default";
	const themeCss = loadThemeCss(theme);
	const lang = data.accessibility?.language ?? "en";
	const contentHtml = buildContentHtml(data);

	const html = `<!DOCTYPE html>
<html lang="${lang}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${data.title} — oh-my-class</title>
  <style>
    /* oh-my-class theme: ${theme} */
    ${themeCss}
  </style>
</head>
<body>
  <header>
    <span class="brand">oh-my-class</span>
  </header>
  <main>
${contentHtml}
  </main>
  <footer>
    <span>Generated by oh-my-class</span>
  </footer>
</body>
</html>`;

	return sanitizeHtml(html);
}

/**
 * Render an Eta template string with data.
 */
export function renderTemplate(
	templateStr: string,
	data: Record<string, unknown>,
): string {
	if (!templateStr) return "";
	const result = eta.renderString(templateStr, data);
	return result ?? "";
}
