/**
 * Core renderer — takes typed artifact data and produces standalone HTML.
 *
 * R2 decision: `renderArtifact<T>()` is the stable public API.
 * Internals rewired from manual HTML generation to `eta.renderAsync()`.
 *
 * All output is self-contained: theme CSS inlined, no CDN, no external assets.
 */

import { eta } from "./eta-engine.js";
import type { ArtifactDataMap, ArtifactType } from "./contracts/index.js";
import { loadTheme } from "./theme/loader.js";
import { sanitizeHtml } from "./sanitizer.js";
import { sanitize } from "./sanitizer/index.js";

/**
 * Render typed artifact data to a sanitized, standalone HTML string.
 *
 * Uses Eta file-based templates: `pages/{type}.html` included in `base.html`.
 * Theme CSS is loaded at runtime and injected into the base template.
 *
 * @example
 * ```ts
 * const html = await renderArtifact('quiz', {
 *   title: 'Test Quiz',
 *   subject: 'English',
 *   gradeLevel: 'Grade 8',
 *   questions: [{ id: 'q1', prompt: '2+2?', options: [{label:'A',text:'3'},{label:'B',text:'4'}], answer: 'B' }],
 * })
 * ```
 */
export async function renderArtifact<T extends ArtifactType>(
  type: T,
  data: ArtifactDataMap[T],
): Promise<string> {
  const themeName = (data as { theme?: string }).theme ?? "default";
  const lang = (data as { lang?: string }).lang ?? "vi";
  const themeCSS = loadTheme(themeName);

  const html = await eta.renderAsync(`pages/${type}`, {
    ...data,
    themeCSS,
    lang,
  });

  return sanitize(html, type);
}

/**
 * Legacy synchronous renderer — kept for backward compatibility.
 * Builds HTML manually without Eta file-based templates.
 *
 * @deprecated Use the async `renderArtifact<T>()` for new code.
 */
export function renderArtifactSync(data: {
  artifact_type: string;
  title: string;
  theme?: string;
  sections?: { title?: string; content?: string }[];
  accessibility?: { language?: string };
}): string {
  const theme = data.theme ?? "default";
  const themeCss = loadTheme(theme);
  const lang = data.accessibility?.language ?? "en";

  const sections = data.sections ?? [];
  const sectionsHtml = sections
    .map((s) => {
      const title = s.title ? `<h2>${s.title}</h2>` : "";
      const content = s.content ? `<p>${s.content}</p>` : "";
      return `    <section>${title}${content}</section>`;
    })
    .join("\n");

  const html = `<!DOCTYPE html>
<html lang="${lang}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${data.title} — oh-my-class</title>
  <style>
    /* oh-my-class theme: ${theme} */
    ${themeCss}
  </style>
</head>
<body>
  <header>
    <span class="brand">oh-my-class</span>
  </header>
  <main>
    <h1>${data.title}</h1>
${sectionsHtml}
  </main>
  <footer>
    <span>Generated by oh-my-class</span>
  </footer>
</body>
</html>`;

  return sanitizeHtml(html);
}

/**
 * Render an Eta template string with data (convenience helper).
 */
export function renderTemplate(
  templateStr: string,
  data: Record<string, unknown>,
): string {
  if (!templateStr) return "";
  const result = eta.renderString(templateStr, data);
  return result ?? "";
}
