import type {
  SlideDeckBlock,
  SlideDeckData,
  SlideDeckInteraction,
  SlideDeckSlide,
} from "./contracts/index.js";
import type {
  SlideDeckChromeVisibility,
  SlideDeckDifferentiationNote,
  SlideDeckDisplayPreferences,
  SlideDeckDisplaySurface,
  SlideDeckInteractionOption,
  SlideDeckPrintLayout,
  SlideDeckRelatedArtifactRef,
  SlideDeckSlidesPerPage,
  SlideDeckTeacherOnly,
} from "./contracts/slide_deck.js";
import { resolveSlideDeckDisplayPreferences } from "./contracts/slide_deck.js";

// ADR-043: the renderer's surface type is the same 5-value surface set as
// display preferences. "presentation" (clean screen teaching) and "review"
// (deterministic internal quality/compliance scanning) join the original
// "student" | "teacher" | "print" trio -- see `normalizeRenderSurface`,
// which maps legacy/unrecognized runtime values onto this set safely.
export type SlideDeckRenderSurface = SlideDeckDisplaySurface;

export type ProjectedSlideDeckOption = Readonly<{
  optionId: string;
  label: string;
  correct: boolean;
}>;

export type ProjectedSlideDeckInteraction = Readonly<{
  interactionId: string;
  interactionType: SlideDeckInteraction["interaction_type"];
  prompt: string;
  options: readonly ProjectedSlideDeckOption[];
  rationale: string;
  acceptableAnswers: readonly string[];
  noJsFallback: string;
  accessibilityLabel: string;
}>;

// ADR-045 (SDTF-03): `label` is the only field ever populated for the
// student/presentation/print surfaces -- a safe pointer like "See Worksheet
// 2". `context` (artifact_type:artifact_id) is teacher/review-only planning
// context and is empty ("") for every other surface, matching how
// `rationale`/`acceptableAnswers` are already surface-gated below.
export type ProjectedSlideDeckRelatedRef = Readonly<{
  label: string;
  context: string;
}>;

export type ProjectedSlideDeckBlock = Readonly<{
  blockId: string;
  blockType: SlideDeckBlock["block_type"];
  body: string;
  mediaAltText: string;
  requiresNetwork: boolean;
  fallbackText: string;
  relatedRefs: readonly ProjectedSlideDeckRelatedRef[];
}>;

// ADR-045 (SDTF-05): teacher-only scaffold/stretch guidance, mirrored 1:1
// from `SlideDeckDifferentiationNote` -- kept as its own field, never merged
// into `answerKeyNotes`, so a leak-check or teacher-panel template can treat
// "how to adapt" and "what the answer is" as distinct surfaces.
export type ProjectedSlideDeckDifferentiationNote = Readonly<{
  level: string;
  guidance: string;
}>;

export type ProjectedSlideDeckSlide = Readonly<{
  slideId: string;
  title: string;
  layout: SlideDeckSlide["layout"];
  revealPolicy: SlideDeckSlide["progression"]["reveal_policy"];
  blocks: readonly ProjectedSlideDeckBlock[];
  interactions: readonly ProjectedSlideDeckInteraction[];
  facilitationNotes: readonly string[];
  answerKeyNotes: readonly string[];
  differentiationGuidance: readonly ProjectedSlideDeckDifferentiationNote[];
  relatedRefs: readonly ProjectedSlideDeckRelatedRef[];
}>;

// ADR-045 (SDTF-02): a deck-level lesson-flow/pacing summary for teacher and
// review only -- role and planned duration are lesson-planning context, not
// student-facing content, so `lessonFlow` stays empty (and
// `totalPlannedMinutes` null) for every other surface.
export type ProjectedSlideDeckLessonFlowEntry = Readonly<{
  slideId: string;
  title: string;
  pedagogicalRole: string;
  plannedMinutes: number | null;
}>;

export type ProjectedSlideDeck = Readonly<{
  deckId: string;
  title: string;
  theme?: string;
  lang: string;
  surface: SlideDeckRenderSurface;
  surfaceLabel: string;
  slides: readonly ProjectedSlideDeckSlide[];
  forbiddenStudentText: readonly string[];
  diagnostics: readonly string[];
  displayPreferences: SlideDeckDisplayPreferences;
  lessonFlow: readonly ProjectedSlideDeckLessonFlowEntry[];
  totalPlannedMinutes: number | null;
  // SDH-02 (ADR-043 decision 6): whether chrome may show "Generated by
  // oh-my-class"-style provenance. Resolved once here from surface + the
  // `chrome` display preference so the template never has to make this call.
  showProvenance: boolean;
  // SDH-03: the initial print-layout CSS class derived from
  // `displayPreferences.print_layout`/`slides_per_page` (see
  // `computeSlideDeckPrintModeClass`). Computed once here so the standalone
  // presentation player's client-side print-mode controls and the
  // server-rendered default share one pairing instead of re-deriving it.
  printModeClass: string;
}>;

// SDH-03: pure paired-value -> CSS class mapping shared by the server-side
// initial render (below) and the standalone HTML's embedded print-mode
// select (which mirrors this exact mapping in vanilla JS, since it has no
// module system to import this from at runtime). Exported so it has one
// test instead of two divergent copies.
export function computeSlideDeckPrintModeClass(
  printLayout: SlideDeckPrintLayout,
  slidesPerPage: SlideDeckSlidesPerPage,
): string {
  if (printLayout === "continuous") return "print-mode--continuous";
  return `print-mode--paged-${slidesPerPage}`;
}

type SlideDeckRenderInput = SlideDeckData & Readonly<{
  render_surface?: SlideDeckRenderSurface;
}>;

// SDE-02 (ADR-041/ADR-047 decision 2): `SlideDeckSlide["layout"]` declares
// the full ADR-041 target vocabulary now, but only these layouts have a
// real renderer template today. Every other declared layout must fail
// closed here — never silently render through a generic fallback template.
const RENDERER_SUPPORTED_SLIDE_LAYOUTS: ReadonlySet<SlideDeckSlide["layout"]> = new Set([
  "title",
  "content",
  "question",
  "activity",
  "summary",
]);

export class SlideDeckUnsupportedLayoutError extends Error {
  readonly layout: string;
  readonly slideId: string;

  constructor(layout: string, slideId: string) {
    super(`Slide "${slideId}" uses layout "${layout}", which has no renderer template yet.`);
    this.name = "SlideDeckUnsupportedLayoutError";
    this.layout = layout;
    this.slideId = slideId;
  }
}

function assertSlideLayoutsAreRenderable(deck: SlideDeckRenderInput): void {
  for (const slide of deck.slides) {
    if (!RENDERER_SUPPORTED_SLIDE_LAYOUTS.has(slide.layout)) {
      throw new SlideDeckUnsupportedLayoutError(slide.layout, slide.slide_id);
    }
  }
}

const KNOWN_RENDER_SURFACES: ReadonlySet<string> = new Set([
  "presentation",
  "student",
  "teacher",
  "print",
  "review",
]);

// ADR-043: `render_surface` crosses the Python/TS JSON boundary untyped, so
// a caller can send any string. Legacy 3-value callers ("student" |
// "teacher" | "print") already match the ADR-043 vocabulary 1:1 and pass
// through unchanged; anything unset/unrecognized falls back to "student" --
// the safest surface -- instead of throwing or silently rendering undefined.
function normalizeRenderSurface(raw: string | undefined): SlideDeckRenderSurface {
  if (raw && KNOWN_RENDER_SURFACES.has(raw)) return raw as SlideDeckRenderSurface;
  return "student";
}

export function projectSlideDeckSurface(deck: SlideDeckRenderInput): ProjectedSlideDeck {
  assertSlideLayoutsAreRenderable(deck);
  const surface = normalizeRenderSurface(deck.render_surface);
  switch (surface) {
    case "student":
      return projectSafeDeck(deck, "student", "Student presentation");
    case "presentation":
      return projectSafeDeck(deck, "presentation", "Presentation");
    case "print":
      return projectPrintDeck(deck);
    case "teacher":
      return projectTeacherDeck(deck, "teacher", "Teacher guide", ["surface:teacher", "projection:teacher-guidance-visible"]);
    case "review":
      return projectTeacherDeck(deck, "review", "Quality review", [
        "surface:review",
        "projection:teacher-guidance-visible",
        "projection:review-deterministic",
      ]);
  }
}

// ADR-043: surfaces whose *projected* object must never carry teacher-only
// data in the first place (checked by the projector functions below).
// `assertStudentSlideDeckHtmlIsSafe` re-checks the rendered HTML string for
// these same surfaces as defense in depth.
const STUDENT_SAFE_SURFACES: ReadonlySet<SlideDeckRenderSurface> = new Set([
  "student",
  "presentation",
  "print",
]);

// SDH-02: the single boundary that guards every student-safe surface
// (student, presentation, print) against teacher-only leakage in the
// *rendered HTML string* -- defense in depth on top of the projector
// functions below, which never put teacher-only data into these surfaces'
// projected object in the first place. Whatever form a leak would take (raw
// JSON, a data attribute, a hidden element, a comment), it has to appear as
// this same substring in the final HTML, so one string-inclusion check
// catches all of them.
export function assertStudentSlideDeckHtmlIsSafe(projected: ProjectedSlideDeck, html: string): void {
  if (!STUDENT_SAFE_SURFACES.has(projected.surface)) return;
  const staticForbidden = ["teacher_only", "teacher_notes", "correct_option_ids", "acceptable_answers", "differentiation_guidance"];
  const leaked = [...staticForbidden, ...projected.forbiddenStudentText]
    .filter((value) => value.length > 0 && html.includes(value));
  if (leaked.length === 0) return;
  throw new SlideDeckStudentLeakError(leaked[0]);
}

export class SlideDeckStudentLeakError extends Error {
  readonly leakedText: string;

  constructor(leakedText: string) {
    super(`Student slide deck HTML leaked teacher-only data: ${leakedText}`);
    this.name = "SlideDeckStudentLeakError";
    this.leakedText = leakedText;
  }
}

// ADR-043 decision 6: student/presentation never show robotic "Generated by
// oh-my-class" branding -- a safety/product rule, not a teacher-configurable
// toggle. Teacher/review are internal-facing and always show provenance.
// Print shows the footer only when the teacher opts in via `chrome`.
function resolveShowProvenance(surface: SlideDeckRenderSurface, chrome: SlideDeckChromeVisibility): boolean {
  switch (surface) {
    case "student":
    case "presentation":
      return false;
    case "print":
      return chrome !== "hidden";
    case "teacher":
    case "review":
      return true;
  }
}

// ADR-043: shared by "student" and "presentation" -- both are safe-share
// surfaces with identical content policy (no teacher-only data), differing
// only in label/diagnostics. "print" stays separate (see projectPrintDeck)
// because it also forces reveals open and drops the JS presentation chrome.
function projectSafeDeck(
  deck: SlideDeckRenderInput,
  surface: SlideDeckRenderSurface,
  surfaceLabel: string,
): ProjectedSlideDeck {
  const displayPreferences = resolveSlideDeckDisplayPreferences(deck.display_preferences);
  return {
    deckId: deck.deck_id,
    title: deck.title,
    theme: deck.theme,
    lang: deck.accessibility.language,
    surface,
    surfaceLabel,
    slides: deck.slides.map((slide) => ({
      slideId: slide.slide_id,
      title: slide.title,
      layout: slide.layout,
      revealPolicy: slide.progression.reveal_policy,
      blocks: projectBlocks(slide.blocks, surface),
      interactions: projectStudentInteractions(slide.interactions ?? []),
      facilitationNotes: [],
      answerKeyNotes: [],
      differentiationGuidance: [],
      relatedRefs: projectRelatedRefs(slide.related_refs ?? [], surface),
    })),
    forbiddenStudentText: forbiddenStudentText(deck),
    diagnostics: [`surface:${surface}`, "projection:teacher-only-stripped"],
    displayPreferences,
    lessonFlow: [],
    totalPlannedMinutes: null,
    showProvenance: resolveShowProvenance(surface, displayPreferences.chrome),
    printModeClass: computeSlideDeckPrintModeClass(displayPreferences.print_layout, displayPreferences.slides_per_page),
  };
}

// ADR-045 (SDTF-04): a future mobile-readable "companion view" -- a
// student's own-device view of interaction prompts, architecturally
// distinct from the projector/presentation surfaces above (which assume a
// shared big-screen 16:9 canvas: full slide layout, blocks, reveal policy).
// `ProjectedCompanionCard` carries no layout/pixel/aspect-ratio field at
// all, so nothing here can force a companion card into projector scaling.
// This is architecture/contract-only for this slice: no live sync
// (TSP-03/04), no student join/auth (TSP-02), no student-response
// persistence -- v1 stays standalone/local-only.
export type ProjectedCompanionCard = Readonly<{
  slideId: string;
  interactionId: string;
  prompt: string;
  responseIntent: SlideDeckInteraction["interaction_type"];
  noJsFallback: string;
  accessibilityLabel: string;
}>;

export type ProjectedCompanionView = Readonly<{
  title: string;
  lang: string;
  surface: SlideDeckRenderSurface;
  cards: readonly ProjectedCompanionCard[];
}>;

// Reuses `projectSafeDeck` -- the same function backing the "student" and
// "presentation" surfaces -- instead of re-deriving student-safety here, so
// a companion card is structurally incapable of carrying teacher-only
// rationale/answer keys: `projectStudentInteractions` (used by
// `projectSafeDeck`) never puts that data into the projected object in the
// first place. Clamps to a student-safe surface regardless of what
// `deck.render_surface` says, so passing "teacher"/"review" can never leak
// a teacher-facing projection into a companion card.
export function projectSlideDeckCompanionCards(
  deck: SlideDeckRenderInput,
  surface: SlideDeckRenderSurface = normalizeRenderSurface(deck.render_surface),
): ProjectedCompanionView {
  const safeSurface = STUDENT_SAFE_SURFACES.has(surface) ? surface : "student";
  const projected = projectSafeDeck(deck, safeSurface, "Student companion");
  return {
    title: projected.title,
    lang: projected.lang,
    surface: projected.surface,
    cards: projected.slides.flatMap((slide) =>
      slide.interactions.map((interaction) => ({
        slideId: slide.slideId,
        interactionId: interaction.interactionId,
        prompt: interaction.prompt,
        responseIntent: interaction.interactionType,
        noJsFallback: interaction.noJsFallback,
        accessibilityLabel: interaction.accessibilityLabel,
      })),
    ),
  };
}

// ADR-043: shared by "teacher" and "review" -- both need full visibility of
// teacher-only data outside the student canvas, differing only in
// label/diagnostics. "review" stays a pure deterministic map over the same
// arrays "teacher" uses (ADR-043 decision 2 / SDH-02 AC5), so a compliance
// scan of review HTML never depends on Set/Map ordering or randomness, and
// never has to treat raw teacher-only data as if it were student-facing.
function projectTeacherDeck(
  deck: SlideDeckRenderInput,
  surface: SlideDeckRenderSurface,
  surfaceLabel: string,
  diagnostics: readonly string[],
): ProjectedSlideDeck {
  const displayPreferences = resolveSlideDeckDisplayPreferences(deck.display_preferences);
  return {
    deckId: deck.deck_id,
    title: deck.title,
    theme: deck.theme,
    lang: deck.accessibility.language,
    surface,
    surfaceLabel,
    slides: deck.slides.map((slide) => ({
      slideId: slide.slide_id,
      title: slide.title,
      layout: slide.layout,
      revealPolicy: slide.progression.reveal_policy,
      blocks: projectBlocks(slide.blocks, surface),
      interactions: projectTeacherInteractions(slide.interactions ?? []),
      facilitationNotes: teacherNotes(slide.teacher_notes).facilitationNotes,
      answerKeyNotes: teacherNotes(slide.teacher_notes).answerKeyNotes,
      differentiationGuidance: projectDifferentiationGuidance(slide.differentiation_guidance ?? []),
      relatedRefs: projectRelatedRefs(slide.related_refs ?? [], surface),
    })),
    forbiddenStudentText: [],
    diagnostics,
    displayPreferences,
    lessonFlow: lessonFlow(deck),
    totalPlannedMinutes: totalPlannedMinutes(deck),
    showProvenance: resolveShowProvenance(surface, displayPreferences.chrome),
    printModeClass: computeSlideDeckPrintModeClass(displayPreferences.print_layout, displayPreferences.slides_per_page),
  };
}

function projectPrintDeck(deck: SlideDeckRenderInput): ProjectedSlideDeck {
  const displayPreferences = resolveSlideDeckDisplayPreferences(deck.display_preferences);
  return {
    deckId: deck.deck_id,
    title: deck.title,
    theme: deck.theme,
    lang: deck.accessibility.language,
    surface: "print",
    surfaceLabel: "Print handout",
    slides: deck.slides.map((slide) => ({
      slideId: slide.slide_id,
      title: slide.title,
      layout: slide.layout,
      revealPolicy: "all_at_once",
      blocks: projectBlocks(slide.blocks, "print"),
      interactions: projectStudentInteractions(slide.interactions ?? []),
      facilitationNotes: [],
      answerKeyNotes: [],
      differentiationGuidance: [],
      relatedRefs: projectRelatedRefs(slide.related_refs ?? [], "print"),
    })),
    forbiddenStudentText: forbiddenStudentText(deck),
    diagnostics: ["surface:print", "projection:reveals-expanded"],
    displayPreferences,
    lessonFlow: [],
    totalPlannedMinutes: null,
    showProvenance: resolveShowProvenance("print", displayPreferences.chrome),
    printModeClass: computeSlideDeckPrintModeClass(displayPreferences.print_layout, displayPreferences.slides_per_page),
  };
}

function lessonFlow(deck: SlideDeckRenderInput): readonly ProjectedSlideDeckLessonFlowEntry[] {
  return deck.slides.map((slide) => ({
    slideId: slide.slide_id,
    title: slide.title,
    pedagogicalRole: slide.pedagogical_role ?? "unassigned",
    plannedMinutes: slide.planned_duration_minutes ?? null,
  }));
}

function totalPlannedMinutes(deck: SlideDeckRenderInput): number | null {
  const minutes = deck.slides
    .map((slide) => slide.planned_duration_minutes)
    .filter((value): value is number => typeof value === "number");
  if (minutes.length === 0) return null;
  return Math.round(minutes.reduce((sum, value) => sum + value, 0) * 10) / 10;
}

function projectBlocks(
  blocks: readonly SlideDeckBlock[],
  surface: SlideDeckRenderSurface,
): readonly ProjectedSlideDeckBlock[] {
  return blocks.map((block) => ({
    blockId: block.block_id,
    blockType: block.block_type,
    body: block.body,
    mediaAltText: block.media?.alt_text ?? "",
    requiresNetwork: block.media?.requires_network ?? false,
    fallbackText: block.media?.fallback_text ?? "",
    relatedRefs: projectRelatedRefs(block.related_refs ?? [], surface),
  }));
}

// ADR-045 (SDTF-03): related-ref pointers never carry the referenced
// artifact's content, so there is nothing to strip for student/presentation/
// print -- only the safe `relationship_label` is ever surfaced there.
// `context` (artifact_type:artifact_id) is added for teacher/review planning
// only.
const TEACHER_VISIBLE_SURFACES: ReadonlySet<SlideDeckRenderSurface> = new Set(["teacher", "review"]);

function projectRelatedRefs(
  refs: readonly SlideDeckRelatedArtifactRef[],
  surface: SlideDeckRenderSurface,
): readonly ProjectedSlideDeckRelatedRef[] {
  return refs.map((ref) => ({
    label: ref.relationship_label,
    context: TEACHER_VISIBLE_SURFACES.has(surface) ? `${ref.artifact_type}:${ref.artifact_id}` : "",
  }));
}

function projectStudentInteractions(interactions: readonly SlideDeckInteraction[]): readonly ProjectedSlideDeckInteraction[] {
  return interactions.map((interaction) => ({
    interactionId: interaction.interaction_id,
    interactionType: interaction.interaction_type,
    prompt: interaction.prompt,
    options: projectOptions(interaction.options ?? [], []),
    rationale: "",
    acceptableAnswers: [],
    noJsFallback: interaction.no_js_fallback ?? "Use this prompt without storing student responses.",
    accessibilityLabel: interaction.accessibility_label ?? "Slide interaction",
  }));
}

function projectTeacherInteractions(interactions: readonly SlideDeckInteraction[]): readonly ProjectedSlideDeckInteraction[] {
  return interactions.map((interaction) => ({
    interactionId: interaction.interaction_id,
    interactionType: interaction.interaction_type,
    prompt: interaction.prompt,
    options: projectOptions(interaction.options ?? [], interaction.teacher_only?.correct_option_ids ?? []),
    rationale: interaction.teacher_only?.rationale ?? "",
    acceptableAnswers: interaction.teacher_only?.acceptable_answers ?? [],
    noJsFallback: interaction.no_js_fallback ?? "Use this prompt without storing student responses.",
    accessibilityLabel: interaction.accessibility_label ?? "Slide interaction",
  }));
}

function projectOptions(
  options: readonly SlideDeckInteractionOption[],
  correctOptionIds: readonly string[],
): readonly ProjectedSlideDeckOption[] {
  return options.map((option) => ({
    optionId: option.option_id,
    label: option.label,
    correct: correctOptionIds.includes(option.option_id),
  }));
}

function teacherNotes(notes: SlideDeckTeacherOnly | null | undefined): Pick<ProjectedSlideDeckSlide, "facilitationNotes" | "answerKeyNotes"> {
  return {
    facilitationNotes: notes?.facilitation_notes ?? [],
    answerKeyNotes: notes?.answer_key_notes ?? [],
  };
}

function projectDifferentiationGuidance(
  notes: readonly SlideDeckDifferentiationNote[],
): readonly ProjectedSlideDeckDifferentiationNote[] {
  return notes.map((note) => ({ level: note.level, guidance: note.guidance }));
}

function forbiddenStudentText(deck: SlideDeckRenderInput): readonly string[] {
  return deck.slides.flatMap((slide) => [
    ...(slide.teacher_notes?.facilitation_notes ?? []),
    ...(slide.teacher_notes?.answer_key_notes ?? []),
    ...(slide.differentiation_guidance ?? []).map((note) => note.guidance),
    ...(slide.interactions ?? []).flatMap((interaction) => [
      ...(interaction.teacher_only?.acceptable_answers ?? []),
      interaction.teacher_only?.rationale ?? "",
    ]),
  ]);
}
