import { questionRegistry } from './registry.js'
import type { QuestionTypeMeta } from './registry.js'

const ALL_FORMATS = ['moet_2025', 'cambridge', 'ielts', 'toefl', 'general'] as const
type F = typeof ALL_FORMATS[number]

const ALL_BLOOM = [
  'remember', 'understand', 'apply', 'analyze', 'evaluate', 'create',
] as const
type B = typeof ALL_BLOOM[number]

const ALL_MOET = ['nhan_biet', 'thong_hieu', 'van_dung', 'van_dung_cao'] as const
type M = typeof ALL_MOET[number]

type Meta = QuestionTypeMeta

const types: Meta[] = [
  // ── choice family ──────────────────────────────────────────────────────────
  {
    type: 'multiple_choice_single',
    family: 'choice',
    label: 'Multiple Choice (Single Answer)',
    labelVi: 'Trắc nghiệm một đáp án',
    artifacts: ['quiz', 'drill', 'worksheet', 'exit_ticket'],
    bloomLevels: ['remember', 'understand', 'apply'] as B[],
    moetLevels: ['nhan_biet', 'thong_hieu', 'van_dung'] as M[],
    subjects: ['all'],
    examFormats: [...ALL_FORMATS] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'low',
    qtiInteraction: 'choiceInteraction',
  },
  {
    type: 'multiple_choice_multiple',
    family: 'choice',
    label: 'Multiple Choice (Multiple Answers)',
    labelVi: 'Trắc nghiệm nhiều đáp án',
    artifacts: ['quiz', 'worksheet'],
    bloomLevels: ['understand', 'apply', 'analyze'] as B[],
    moetLevels: ['thong_hieu', 'van_dung'] as M[],
    subjects: ['all'],
    examFormats: [...ALL_FORMATS] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'low',
    qtiInteraction: 'choiceInteraction',
  },
  {
    type: 'true_false_4item',
    family: 'choice',
    label: 'True/False 4-Item (MOET 2025)',
    labelVi: 'Đúng/Sai 4 ý (MOET 2025)',
    artifacts: ['quiz', 'drill'],
    bloomLevels: ['remember', 'understand'] as B[],
    moetLevels: ['nhan_biet', 'thong_hieu'] as M[],
    subjects: ['all'],
    examFormats: ['moet_2025'] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'low',
    qtiInteraction: 'choiceInteraction',
  },
  {
    type: 'phonics',
    family: 'choice',
    label: 'Phonics',
    labelVi: 'Ngữ âm',
    artifacts: ['drill', 'worksheet'],
    bloomLevels: ['remember', 'understand'] as B[],
    moetLevels: ['nhan_biet'] as M[],
    subjects: ['english'],
    examFormats: ['general', 'cambridge'] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'low',
    qtiInteraction: 'choiceInteraction',
  },
  // ── text-entry family ──────────────────────────────────────────────────────
  {
    type: 'cloze',
    family: 'text-entry',
    label: 'Cloze (Free)',
    labelVi: 'Điền vào chỗ trống (tự do)',
    artifacts: ['quiz', 'worksheet', 'drill'],
    bloomLevels: ['understand', 'apply'] as B[],
    moetLevels: ['thong_hieu', 'van_dung'] as M[],
    subjects: ['english', 'literature'],
    examFormats: [...ALL_FORMATS] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'low',
    qtiInteraction: 'textEntryInteraction',
  },
  {
    type: 'short_answer',
    family: 'text-entry',
    label: 'Short Answer',
    labelVi: 'Trả lời ngắn',
    artifacts: ['quiz', 'worksheet', 'exit_ticket'],
    bloomLevels: ['remember', 'understand', 'apply'] as B[],
    moetLevels: ['nhan_biet', 'thong_hieu', 'van_dung'] as M[],
    subjects: ['all'],
    examFormats: [...ALL_FORMATS] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'low',
    qtiInteraction: 'textEntryInteraction',
  },
  {
    type: 'grammar_transformation',
    family: 'text-entry',
    label: 'Grammar Transformation',
    labelVi: 'Viết lại câu (ngữ pháp)',
    artifacts: ['worksheet', 'drill'],
    bloomLevels: ['apply', 'analyze'] as B[],
    moetLevels: ['van_dung'] as M[],
    subjects: ['english'],
    examFormats: ['moet_2025', 'cambridge', 'ielts'] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'medium',
    qtiInteraction: 'textEntryInteraction',
  },
  {
    type: 'reported_speech',
    family: 'text-entry',
    label: 'Reported Speech',
    labelVi: 'Câu tường thuật',
    artifacts: ['worksheet', 'drill'],
    bloomLevels: ['apply'] as B[],
    moetLevels: ['van_dung'] as M[],
    subjects: ['english'],
    examFormats: ['moet_2025', 'cambridge'] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'medium',
    qtiInteraction: 'textEntryInteraction',
  },
  {
    type: 'passive_voice',
    family: 'text-entry',
    label: 'Passive Voice',
    labelVi: 'Câu bị động',
    artifacts: ['worksheet', 'drill'],
    bloomLevels: ['apply'] as B[],
    moetLevels: ['van_dung'] as M[],
    subjects: ['english'],
    examFormats: ['moet_2025', 'cambridge'] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'medium',
    qtiInteraction: 'textEntryInteraction',
  },
  {
    type: 'conditional_builder',
    family: 'text-entry',
    label: 'Conditional Builder',
    labelVi: 'Câu điều kiện',
    artifacts: ['worksheet'],
    bloomLevels: ['apply', 'analyze'] as B[],
    moetLevels: ['van_dung'] as M[],
    subjects: ['english'],
    examFormats: ['moet_2025', 'cambridge', 'ielts'] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'medium',
    qtiInteraction: 'textEntryInteraction',
  },
  {
    type: 'error_correction',
    family: 'text-entry',
    label: 'Error Correction',
    labelVi: 'Sửa lỗi',
    artifacts: ['worksheet', 'drill'],
    bloomLevels: ['analyze'] as B[],
    moetLevels: ['van_dung', 'van_dung_cao'] as M[],
    subjects: ['english'],
    examFormats: ['moet_2025', 'cambridge', 'ielts'] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'medium',
    qtiInteraction: 'textEntryInteraction',
  },
  {
    type: 'sentence_manipulation',
    family: 'text-entry',
    label: 'Sentence Manipulation',
    labelVi: 'Biến đổi câu',
    artifacts: ['worksheet'],
    bloomLevels: ['apply', 'analyze'] as B[],
    moetLevels: ['van_dung'] as M[],
    subjects: ['english'],
    examFormats: ['moet_2025', 'cambridge'] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'medium',
    qtiInteraction: 'textEntryInteraction',
  },
  {
    type: 'reading_comprehension',
    family: 'text-entry',
    label: 'Reading Comprehension',
    labelVi: 'Đọc hiểu',
    artifacts: ['quiz', 'worksheet'],
    bloomLevels: ['understand', 'apply', 'analyze'] as B[],
    moetLevels: ['thong_hieu', 'van_dung', 'van_dung_cao'] as M[],
    subjects: ['english', 'literature'],
    examFormats: [...ALL_FORMATS] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'high',
    qtiInteraction: 'textEntryInteraction',
  },
  // ── fill-gap family ────────────────────────────────────────────────────────
  {
    type: 'fill_blank_wordbank',
    family: 'fill-gap',
    label: 'Fill in the Blank (Word Bank)',
    labelVi: 'Điền từ (có từ gợi ý)',
    artifacts: ['worksheet', 'drill'],
    bloomLevels: ['remember', 'understand', 'apply'] as B[],
    moetLevels: ['nhan_biet', 'thong_hieu', 'van_dung'] as M[],
    subjects: ['all'],
    examFormats: [...ALL_FORMATS] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'low',
    qtiInteraction: 'inlineChoiceInteraction',
  },
  {
    type: 'cloze_mixed',
    family: 'fill-gap',
    label: 'Cloze Mixed',
    labelVi: 'Điền từ hỗn hợp',
    artifacts: ['quiz', 'worksheet'],
    bloomLevels: ['apply', 'analyze'] as B[],
    moetLevels: ['van_dung'] as M[],
    subjects: ['english'],
    examFormats: ['moet_2025', 'cambridge', 'ielts', 'toefl'] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'medium',
    qtiInteraction: 'inlineChoiceInteraction',
  },
  {
    type: 'dialogue_completion',
    family: 'fill-gap',
    label: 'Dialogue Completion',
    labelVi: 'Hoàn thành đoạn hội thoại',
    artifacts: ['worksheet'],
    bloomLevels: ['apply'] as B[],
    moetLevels: ['van_dung'] as M[],
    subjects: ['english'],
    examFormats: ['moet_2025', 'cambridge'] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'medium',
    qtiInteraction: 'inlineChoiceInteraction',
  },
  // ── match family ───────────────────────────────────────────────────────────
  {
    type: 'matching',
    family: 'match',
    label: 'Matching',
    labelVi: 'Nối đôi',
    artifacts: ['quiz', 'worksheet', 'drill'],
    bloomLevels: ['remember', 'understand'] as B[],
    moetLevels: ['nhan_biet', 'thong_hieu'] as M[],
    subjects: ['all'],
    examFormats: [...ALL_FORMATS] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'low',
    qtiInteraction: 'matchInteraction',
  },
  {
    type: 'matching_vocabulary',
    family: 'match',
    label: 'Vocabulary Matching',
    labelVi: 'Nối từ vựng',
    artifacts: ['worksheet', 'drill'],
    bloomLevels: ['remember', 'understand'] as B[],
    moetLevels: ['nhan_biet', 'thong_hieu'] as M[],
    subjects: ['english'],
    examFormats: [...ALL_FORMATS] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'low',
    qtiInteraction: 'matchInteraction',
  },
  {
    type: 'collocation',
    family: 'match',
    label: 'Collocation',
    labelVi: 'Kết hợp từ',
    artifacts: ['worksheet'],
    bloomLevels: ['understand', 'apply'] as B[],
    moetLevels: ['thong_hieu', 'van_dung'] as M[],
    subjects: ['english'],
    examFormats: ['moet_2025', 'cambridge', 'ielts'] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'medium',
    qtiInteraction: 'matchInteraction',
  },
  {
    type: 'idioms',
    family: 'match',
    label: 'Idioms',
    labelVi: 'Thành ngữ',
    artifacts: ['worksheet'],
    bloomLevels: ['understand', 'apply'] as B[],
    moetLevels: ['thong_hieu', 'van_dung'] as M[],
    subjects: ['english'],
    examFormats: ['cambridge', 'ielts', 'toefl'] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'medium',
    qtiInteraction: 'matchInteraction',
  },
  {
    type: 'word_analysis',
    family: 'match',
    label: 'Word Analysis',
    labelVi: 'Phân tích từ',
    artifacts: ['worksheet'],
    bloomLevels: ['analyze'] as B[],
    moetLevels: ['van_dung', 'van_dung_cao'] as M[],
    subjects: ['english'],
    examFormats: ['cambridge', 'ielts'] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'medium',
    qtiInteraction: 'matchInteraction',
  },
  // ── order family ───────────────────────────────────────────────────────────
  {
    type: 'ordering',
    family: 'order',
    label: 'Ordering',
    labelVi: 'Sắp xếp',
    artifacts: ['worksheet', 'drill'],
    bloomLevels: ['understand', 'apply'] as B[],
    moetLevels: ['thong_hieu', 'van_dung'] as M[],
    subjects: ['all'],
    examFormats: [...ALL_FORMATS] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'low',
    qtiInteraction: 'orderInteraction',
  },
  {
    type: 'tense_timeline',
    family: 'order',
    label: 'Tense Timeline',
    labelVi: 'Trục thời gian thì',
    artifacts: ['worksheet'],
    bloomLevels: ['apply', 'analyze'] as B[],
    moetLevels: ['van_dung'] as M[],
    subjects: ['english'],
    examFormats: ['moet_2025', 'cambridge'] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'medium',
    qtiInteraction: 'orderInteraction',
  },
  {
    type: 'vocabulary_scaffolded',
    family: 'order',
    label: 'Vocabulary Scaffolded',
    labelVi: 'Từ vựng theo tầng',
    artifacts: ['lesson', 'worksheet'],
    bloomLevels: ['remember', 'understand', 'apply', 'create'] as B[],
    moetLevels: ['nhan_biet', 'thong_hieu', 'van_dung'] as M[],
    subjects: ['english'],
    examFormats: ['general', 'cambridge'] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'high',
    qtiInteraction: 'orderInteraction',
  },
  // ── open family ────────────────────────────────────────────────────────────
  {
    type: 'essay',
    family: 'open',
    label: 'Essay',
    labelVi: 'Bài luận',
    artifacts: ['worksheet'],
    bloomLevels: ['evaluate', 'create'] as B[],
    moetLevels: ['van_dung_cao'] as M[],
    subjects: ['all'],
    examFormats: [...ALL_FORMATS] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'high',
    qtiInteraction: 'extendedTextInteraction',
  },
  {
    type: 'paraphrase',
    family: 'open',
    label: 'Paraphrase',
    labelVi: 'Diễn đạt lại',
    artifacts: ['worksheet'],
    bloomLevels: ['understand', 'apply', 'evaluate'] as B[],
    moetLevels: ['van_dung', 'van_dung_cao'] as M[],
    subjects: ['english'],
    examFormats: ['moet_2025', 'cambridge', 'ielts'] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'high',
    qtiInteraction: 'extendedTextInteraction',
  },
  {
    type: 'translation',
    family: 'open',
    label: 'Translation',
    labelVi: 'Dịch',
    artifacts: ['worksheet'],
    bloomLevels: ['apply', 'evaluate'] as B[],
    moetLevels: ['van_dung', 'van_dung_cao'] as M[],
    subjects: ['english'],
    examFormats: ['moet_2025'] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'high',
    qtiInteraction: 'extendedTextInteraction',
  },
  {
    type: 'lab_report',
    family: 'open',
    label: 'Lab Report',
    labelVi: 'Báo cáo thí nghiệm',
    artifacts: ['worksheet'],
    bloomLevels: ['apply', 'analyze', 'evaluate'] as B[],
    moetLevels: ['van_dung', 'van_dung_cao'] as M[],
    subjects: ['science'],
    examFormats: ['general', 'moet_2025'] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'high',
    qtiInteraction: 'extendedTextInteraction',
  },
  {
    type: 'drawing',
    family: 'open',
    label: 'Drawing',
    labelVi: 'Vẽ hình',
    artifacts: ['worksheet'],
    bloomLevels: ['apply', 'create'] as B[],
    moetLevels: ['van_dung'] as M[],
    subjects: ['math', 'science'],
    examFormats: ['general', 'moet_2025'] as F[],
    requiresMedia: false,
    isInteractive: true,
    complexity: 'medium',
    qtiInteraction: 'extendedTextInteraction',
  },
  {
    type: 'performance',
    family: 'open',
    label: 'Performance Task',
    labelVi: 'Bài thực hành',
    artifacts: ['worksheet'],
    bloomLevels: ['apply', 'evaluate', 'create'] as B[],
    moetLevels: ['van_dung', 'van_dung_cao'] as M[],
    subjects: ['all'],
    examFormats: ['general'] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'high',
    qtiInteraction: 'extendedTextInteraction',
  },
  {
    type: 'dictation',
    family: 'open',
    label: 'Dictation',
    labelVi: 'Nghe chép',
    artifacts: ['drill'],
    bloomLevels: ['remember', 'understand'] as B[],
    moetLevels: ['nhan_biet', 'thong_hieu'] as M[],
    subjects: ['english'],
    examFormats: ['general', 'cambridge'] as F[],
    requiresMedia: true,
    isInteractive: false,
    complexity: 'medium',
    qtiInteraction: 'extendedTextInteraction',
  },
  // ── interactive family ─────────────────────────────────────────────────────
  {
    type: 'drag_and_drop',
    family: 'interactive',
    label: 'Drag and Drop',
    labelVi: 'Kéo và thả',
    artifacts: ['quiz', 'worksheet'],
    bloomLevels: ['remember', 'understand', 'apply'] as B[],
    moetLevels: ['nhan_biet', 'thong_hieu', 'van_dung'] as M[],
    subjects: ['all'],
    examFormats: ['general'] as F[],
    requiresMedia: false,
    isInteractive: true,
    complexity: 'medium',
    qtiInteraction: 'associateInteraction',
  },
  {
    type: 'branching_scenario',
    family: 'interactive',
    label: 'Branching Scenario',
    labelVi: 'Tình huống phân nhánh',
    artifacts: ['lesson'],
    bloomLevels: ['apply', 'analyze', 'evaluate'] as B[],
    moetLevels: ['van_dung', 'van_dung_cao'] as M[],
    subjects: ['all'],
    examFormats: ['general'] as F[],
    requiresMedia: false,
    isInteractive: true,
    complexity: 'high',
    qtiInteraction: 'associateInteraction',
  },
  {
    type: 'step_by_step_math',
    family: 'interactive',
    label: 'Step-by-Step Math (CGI)',
    labelVi: 'Toán từng bước (CGI)',
    artifacts: ['worksheet', 'drill'],
    bloomLevels: ['apply', 'analyze'] as B[],
    moetLevels: ['van_dung'] as M[],
    subjects: ['math'],
    examFormats: ['general', 'moet_2025'] as F[],
    requiresMedia: false,
    isInteractive: true,
    complexity: 'high',
    qtiInteraction: 'associateInteraction',
  },
  {
    type: 'geometric_proof',
    family: 'interactive',
    label: 'Geometric Proof',
    labelVi: 'Chứng minh hình học',
    artifacts: ['worksheet'],
    bloomLevels: ['analyze', 'evaluate'] as B[],
    moetLevels: ['van_dung', 'van_dung_cao'] as M[],
    subjects: ['math'],
    examFormats: ['general', 'moet_2025'] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'high',
    qtiInteraction: 'associateInteraction',
  },
  {
    type: 'data_interpretation',
    family: 'interactive',
    label: 'Data Interpretation',
    labelVi: 'Đọc biểu đồ / bảng số liệu',
    artifacts: ['quiz', 'worksheet'],
    bloomLevels: ['analyze', 'evaluate'] as B[],
    moetLevels: ['van_dung', 'van_dung_cao'] as M[],
    subjects: ['math', 'science'],
    examFormats: ['general', 'moet_2025', 'cambridge'] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'medium',
    qtiInteraction: 'associateInteraction',
  },
  {
    type: 'coding_exercise',
    family: 'interactive',
    label: 'Coding Exercise',
    labelVi: 'Bài lập trình',
    artifacts: ['worksheet'],
    bloomLevels: ['apply', 'analyze', 'create'] as B[],
    moetLevels: ['van_dung', 'van_dung_cao'] as M[],
    subjects: ['informatics'],
    examFormats: ['general', 'moet_2025'] as F[],
    requiresMedia: false,
    isInteractive: true,
    complexity: 'high',
    qtiInteraction: 'associateInteraction',
  },
  {
    type: 'financial_literacy',
    family: 'interactive',
    label: 'Financial Literacy',
    labelVi: 'Tài chính cá nhân',
    artifacts: ['worksheet'],
    bloomLevels: ['apply', 'analyze'] as B[],
    moetLevels: ['van_dung'] as M[],
    subjects: ['math'],
    examFormats: ['general'] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'medium',
    qtiInteraction: 'associateInteraction',
  },
  {
    type: 'measurement',
    family: 'interactive',
    label: 'Measurement',
    labelVi: 'Đo lường',
    artifacts: ['worksheet', 'drill'],
    bloomLevels: ['apply'] as B[],
    moetLevels: ['van_dung'] as M[],
    subjects: ['math', 'science'],
    examFormats: ['general', 'moet_2025'] as F[],
    requiresMedia: false,
    isInteractive: false,
    complexity: 'low',
    qtiInteraction: 'associateInteraction',
  },
  // ── multimedia family ──────────────────────────────────────────────────────
  {
    type: 'multimedia_video',
    family: 'multimedia',
    label: 'Video Recording',
    labelVi: 'Quay video',
    artifacts: ['worksheet'],
    bloomLevels: ['apply', 'create'] as B[],
    moetLevels: ['van_dung', 'van_dung_cao'] as M[],
    subjects: ['all'],
    examFormats: ['general'] as F[],
    requiresMedia: true,
    isInteractive: false,
    complexity: 'medium',
    qtiInteraction: 'uploadInteraction',
  },
  {
    type: 'multimedia_audio',
    family: 'multimedia',
    label: 'Audio Recording',
    labelVi: 'Thu âm',
    artifacts: ['worksheet', 'drill'],
    bloomLevels: ['apply', 'create'] as B[],
    moetLevels: ['van_dung'] as M[],
    subjects: ['english'],
    examFormats: ['general', 'cambridge', 'ielts'] as F[],
    requiresMedia: true,
    isInteractive: false,
    complexity: 'medium',
    qtiInteraction: 'uploadInteraction',
  },
  {
    type: 'multimedia_photo',
    family: 'multimedia',
    label: 'Photo Documentation',
    labelVi: 'Chụp ảnh / ghi nhận',
    artifacts: ['worksheet'],
    bloomLevels: ['apply', 'create'] as B[],
    moetLevels: ['van_dung'] as M[],
    subjects: ['science', 'all'],
    examFormats: ['general'] as F[],
    requiresMedia: true,
    isInteractive: false,
    complexity: 'low',
    qtiInteraction: 'uploadInteraction',
  },
  {
    type: 'experiment_documentation',
    family: 'multimedia',
    label: 'Experiment Documentation',
    labelVi: 'Ghi nhận thí nghiệm',
    artifacts: ['worksheet'],
    bloomLevels: ['apply', 'analyze'] as B[],
    moetLevels: ['van_dung', 'van_dung_cao'] as M[],
    subjects: ['science'],
    examFormats: ['general', 'moet_2025'] as F[],
    requiresMedia: true,
    isInteractive: false,
    complexity: 'medium',
    qtiInteraction: 'uploadInteraction',
  },
  {
    type: 'parent_child_activity',
    family: 'multimedia',
    label: 'Parent-Child Activity',
    labelVi: 'Hoạt động phụ huynh - học sinh',
    artifacts: ['worksheet'],
    bloomLevels: ['apply', 'create'] as B[],
    moetLevels: ['van_dung'] as M[],
    subjects: ['all'],
    examFormats: ['general'] as F[],
    requiresMedia: true,
    isInteractive: false,
    complexity: 'medium',
    qtiInteraction: 'uploadInteraction',
  },
  {
    type: 'field_trip_journal',
    family: 'multimedia',
    label: 'Field Trip Journal',
    labelVi: 'Nhật ký tham quan',
    artifacts: ['worksheet'],
    bloomLevels: ['apply', 'analyze', 'create'] as B[],
    moetLevels: ['van_dung', 'van_dung_cao'] as M[],
    subjects: ['all'],
    examFormats: ['general'] as F[],
    requiresMedia: true,
    isInteractive: false,
    complexity: 'medium',
    qtiInteraction: 'uploadInteraction',
  },
  {
    type: 'art_project',
    family: 'multimedia',
    label: 'Art Project',
    labelVi: 'Dự án nghệ thuật',
    artifacts: ['worksheet'],
    bloomLevels: ['create', 'evaluate'] as B[],
    moetLevels: ['van_dung_cao'] as M[],
    subjects: ['all'],
    examFormats: ['general'] as F[],
    requiresMedia: true,
    isInteractive: false,
    complexity: 'medium',
    qtiInteraction: 'uploadInteraction',
  },
]

// Auto-register at module init (EV-singleton pattern)
for (const meta of types) {
  questionRegistry.register(meta)
}
