"""Step 12 — Finalize: render standalone HTML and persist exports."""

from __future__ import annotations

import html
from typing import Any

from packages.agents.state import (
    OhMyClassState,  # noqa: TC001  needed at runtime for LangGraph get_type_hints
)

_SYSTEM_FONT_STACK = (
    "system-ui, -apple-system, 'Segoe UI', Roboto, "
    "'Helvetica Neue', Arial, sans-serif"
)


def _render_artifact_to_html(artifact: dict[str, Any]) -> str:
    """Render a single artifact dict to standalone HTML.

    Produces self-contained HTML with:
    - DOCTYPE
    - No external assets (CDN, http links)
    - oh-my-class brand string
    - Responsive viewport meta
    - Inline CSS
    - System font stack only
    """
    title = html.escape(artifact.get("title", "Untitled"))
    theme = artifact.get("theme", "default")
    artifact_type = artifact.get("artifact_type", "lesson")
    sections = artifact.get("sections", [])
    lang = artifact.get("accessibility", {}).get("language", "vi")

    sections_html = ""
    for section in sections:
        if section.get("teacher_only"):
            continue
        sec_title = html.escape(section.get("title", ""))
        sec_content = html.escape(section.get("content", ""))
        if sec_title:
            sections_html += f'    <h2>{sec_title}</h2>\n'
        if sec_content:
            sections_html += f"    <p>{sec_content}</p>\n"

    font_rule = (
        f"    body {{ font-family: {_SYSTEM_FONT_STACK};"
        " line-height: 1.6; padding: 2rem;"
        " max-width: 800px; margin: 0 auto; }}\n"
    )
    footer_rule = (
        "    footer { border-top: 1px solid #ddd;"
        " margin-top: 2rem; padding-top: 1rem;"
        " font-size: 0.875rem; color: #666; }\n"
    )
    print_rule = (
        "    @media print { .no-print { display: none; }"
        " .page-break { page-break-after: always; } }\n"
    )
    meta_line = (
        f'    <p class="no-print" style="font-size:0.875rem;'
        f'color:#888;">Type: {artifact_type}'
        f" | Theme: {theme}</p>\n"
    )

    return (
        '<!DOCTYPE html>\n'
        f'<html lang="{lang}">\n'
        "<head>\n"
        '  <meta charset="UTF-8">\n'
        '  <meta name="viewport"'
        ' content="width=device-width, initial-scale=1.0">\n'
        f"  <title>{title} — oh-my-class</title>\n"
        "  <style>\n"
        f"    /* oh-my-class theme: {theme} */\n"
        "    * { margin: 0; padding: 0;"
        " box-sizing: border-box; }\n"
        f"{font_rule}"
        "    header { border-bottom: 2px solid #333;"
        " margin-bottom: 2rem; padding-bottom: 1rem; }\n"
        "    .brand { font-weight: bold; color: #2563eb; }\n"
        "    h1 { font-size: 1.5rem; margin-bottom: 1rem; }\n"
        "    h2 { font-size: 1.2rem;"
        " margin: 1.5rem 0 0.5rem; }\n"
        "    p { margin-bottom: 1rem; }\n"
        f"{footer_rule}"
        f"{print_rule}"
        "  </style>\n"
        "</head>\n"
        "<body>\n"
        "  <header>\n"
        '    <span class="brand">oh-my-class</span>\n'
        "  </header>\n"
        "  <main>\n"
        f"    <h1>{title}</h1>\n"
        f"{meta_line}"
        f"{sections_html}"
        "  </main>\n"
        "  <footer>\n"
        "    <span>Generated by oh-my-class</span>\n"
        "  </footer>\n"
        "</body>\n"
        "</html>"
    )


def step_12_finalize(state: OhMyClassState) -> dict[str, Any]:
    """Render artifacts to standalone HTML and record exported files."""
    artifacts = state.get("artifacts") or []
    export_formats = state.get("export_formats") or ["html"]

    exported_files: list[dict[str, Any]] = []

    if "html" in export_formats:
        for i, artifact in enumerate(artifacts):
            if artifact.get("teacher_only"):
                continue

            rendered_html = _render_artifact_to_html(artifact)
            artifact_id = artifact.get(
                "artifact_id", f"artifact-{i}"
            )
            title = artifact.get("title", f"Artifact {i}")

            exported_files.append({
                "artifact_id": artifact_id,
                "format": "html",
                "title": title,
                "content": rendered_html,
                "artifact_type": artifact.get(
                    "artifact_type", "unknown"
                ),
                "theme": artifact.get("theme", "default"),
            })

    return {
        "exported_files": exported_files,
        "current_step": 12,
    }
