"""TeachingSession lifecycle, privacy, retention, join, role tokens,
response collection/analytics governance, and live event-log/sync (TSP-01/
02/03/05, ADR-046).

Live routes (`routers/teaching_session_live.py`) are the runtime surface;
cockpit UI is still TSP-04. See `.scratch/teaching-session-platform/issues/`.
"""

from .delivery_mode import (
    DELIVERY_MODE_POLICIES,
    IMPLEMENTED_DELIVERY_MODES,
    DeliveryModePolicy,
    describe_delivery_mode_policy,
)
from .event_log import (
    DEFAULT_RECOVERY_EVENT_LIMIT,
    RecordedEvent,
    append_event,
    find_by_idempotency_key,
    record_event,
    recover_read_model,
    replay_events,
    row_to_event,
)
from .events import (
    SessionEvent,
    SessionEventType,
    SessionReadModel,
    apply_event,
    build_event,
    initial_read_model,
)
from .join import (
    JOINABLE_STATUSES,
    JoinAccepted,
    JoinRateLimitState,
    JoinRejected,
    allow_join_attempt,
    find_joinable_session_by_room_code,
    generate_room_code,
    is_room_code_valid,
    join_session,
    room_code_join_payload,
)
from .models import (
    ClassRosterEntry,
    DeliveryMode,
    RetentionTier,
    SessionAuditEvent,
    SessionDataCategory,
    SessionStatus,
    TeachingSession,
    TeachingSessionEvent,
)
from .recap import (
    RecapRejected,
    RecapStatus,
    SessionClassRecap,
    build_recap_text,
    generate_class_recap,
    get_shared_recap,
    share_class_recap,
    update_class_recap_draft,
)
from .recommendations import (
    RECOMMENDATION_ARTIFACT_TYPES,
    RecommendationCandidate,
    RecommendationKind,
    RecommendationStatus,
    SessionRecommendation,
    approve_recommendation,
    create_pending_recommendation,
    generate_recommendation_candidates,
)
from .responses import (
    STRUCTURED_RESPONSE_KINDS,
    DrillDownAccepted,
    DrillDownRejected,
    FreeTextAccepted,
    FreeTextRejected,
    GamificationMode,
    MisconceptionRollupRow,
    ResponseAccepted,
    ResponseKind,
    ResponseRejected,
    SessionResponseAggregate,
    SessionStudentResponse,
    StudentDrillDownRow,
    class_collective_points,
    class_concept_rollup,
    gamification_mode_from_preference,
    gate_free_text,
    get_session_aggregates,
    get_session_raw_responses,
    private_student_points,
    record_response,
    student_drill_down,
)
from .retention import (
    RetentionPolicyDescription,
    RetentionSelectionAccepted,
    RetentionSelectionRejected,
    allowed_data_categories_for_tier,
    describe_retention_policy,
    is_prunable,
    validate_retention_selection,
)
from .roster import (
    RosterImportError,
    get_roster_entry,
    import_roster,
    list_roster,
    parse_roster_csv,
)
from .service import create_session
from .session_auth import get_session_claims, require_controller, require_session_role
from .status import (
    SessionTransitionAccepted,
    SessionTransitionRejected,
    validate_session_transition,
)
from .tokens import (
    PARTICIPANT_ROLES,
    TEACHER_MINTED_ROLES,
    IdentityMode,
    SessionRole,
    SessionTokenPayload,
    mint_session_token,
    verify_session_token,
)

__all__ = [
    "DELIVERY_MODE_POLICIES",
    "DEFAULT_RECOVERY_EVENT_LIMIT",
    "IMPLEMENTED_DELIVERY_MODES",
    "JOINABLE_STATUSES",
    "PARTICIPANT_ROLES",
    "RECOMMENDATION_ARTIFACT_TYPES",
    "STRUCTURED_RESPONSE_KINDS",
    "TEACHER_MINTED_ROLES",
    "ClassRosterEntry",
    "DeliveryMode",
    "DeliveryModePolicy",
    "DrillDownAccepted",
    "DrillDownRejected",
    "FreeTextAccepted",
    "FreeTextRejected",
    "GamificationMode",
    "IdentityMode",
    "JoinAccepted",
    "JoinRateLimitState",
    "JoinRejected",
    "MisconceptionRollupRow",
    "RecapRejected",
    "RecapStatus",
    "RecommendationCandidate",
    "RecommendationKind",
    "RecommendationStatus",
    "RecordedEvent",
    "ResponseAccepted",
    "ResponseKind",
    "ResponseRejected",
    "RetentionPolicyDescription",
    "RetentionSelectionAccepted",
    "RetentionSelectionRejected",
    "RetentionTier",
    "RosterImportError",
    "SessionAuditEvent",
    "SessionClassRecap",
    "SessionDataCategory",
    "SessionEvent",
    "SessionEventType",
    "SessionReadModel",
    "SessionRecommendation",
    "SessionResponseAggregate",
    "SessionRole",
    "SessionStatus",
    "SessionStudentResponse",
    "SessionTokenPayload",
    "SessionTransitionAccepted",
    "SessionTransitionRejected",
    "StudentDrillDownRow",
    "TeachingSession",
    "TeachingSessionEvent",
    "allow_join_attempt",
    "allowed_data_categories_for_tier",
    "append_event",
    "apply_event",
    "approve_recommendation",
    "build_event",
    "build_recap_text",
    "class_collective_points",
    "class_concept_rollup",
    "create_pending_recommendation",
    "create_session",
    "describe_delivery_mode_policy",
    "describe_retention_policy",
    "find_by_idempotency_key",
    "find_joinable_session_by_room_code",
    "gamification_mode_from_preference",
    "gate_free_text",
    "generate_class_recap",
    "generate_recommendation_candidates",
    "generate_room_code",
    "get_roster_entry",
    "get_session_aggregates",
    "get_session_claims",
    "get_session_raw_responses",
    "get_shared_recap",
    "import_roster",
    "initial_read_model",
    "is_prunable",
    "is_room_code_valid",
    "join_session",
    "list_roster",
    "mint_session_token",
    "parse_roster_csv",
    "private_student_points",
    "record_event",
    "record_response",
    "recover_read_model",
    "replay_events",
    "require_controller",
    "require_session_role",
    "room_code_join_payload",
    "row_to_event",
    "share_class_recap",
    "student_drill_down",
    "update_class_recap_draft",
    "validate_retention_selection",
    "validate_session_transition",
    "verify_session_token",
]
