"""Shared contracts package — Pydantic v2 models for the oh-my-class pipeline.

All schema contracts live here. Agents and quality gates reference these models
rather than defining their own. This is the single source of truth for data shapes.
"""

from common.contracts.answer_key import AnswerKeyContent, AnswerKeyMetadata, AnswerKeySection
from common.contracts.artifact import ArtifactContent, Flashcard, FlashcardDeckData, TeachingPack
from common.contracts.artifact_workflow import ArtifactGenerationInput, ArtifactWorkflowState
from common.contracts.auth import Role, Token, User
from common.contracts.class_profile import ClassProfile, LearningPreferences
from common.contracts.components import ContentComponent
from common.contracts.component_strategy import (
    ArtifactStrategyProjection,
    ComponentStrategyMode,
    ComponentStrategyPlan,
    ComponentStrategyRequest,
    ComponentStrategyResult,
    ComponentStrategyStatus,
    ComplianceSafety,
    ExportProjectionState,
    ExportProjectionStatus,
    FallbackMetadata,
    FeedbackEventType,
    FeedbackSource,
    ObjectiveRef,
    ObjectiveCoverage,
    PrerequisiteRisk,
    ResearchRiskLevel,
    ResearchSignals,
    RevisionActor,
    SourceConfidence,
    StrategyBlockingIssue,
    StrategyBlockingIssueCode,
    StrategyFeedbackEvent,
    StrategyQualityScore,
    StrategyRevision,
    StrategyRevisionMateriality,
    StrategySlot,
    StrategySlotBudget,
    StrategyVariant,
    StrategyWarning,
    StrategyWarningCode,
    TeacherPreferenceSignals,
)
from common.contracts.component_strategy_privacy import (
    StrategyDecisionLedger,
    StrategyObservabilitySummary,
    StrategyRequestFingerprint,
)
from common.contracts.diagnostic_report import (
    BloomGap,
    DiagnosticReport,
    KnowledgeGap,
    MisconceptionPattern,
)
from common.contracts.errors import (
    ErrorCode,
    ErrorResponse,
    PipelineErrorResponse,
    ValidationErrorDetail,
)
from common.contracts.judge_output import JudgeOutput, LayerScore
from common.contracts.inverse_thinking import (
    InverseThinkingCase,
    InverseThinkingPack,
    InverseThinkingStudentChallenge,
    InverseThinkingSummaryRow,
    InverseThinkingTeacherOnly,
)
from common.contracts.lesson_plan import AssessmentCheckpoint, LearningObjective, LessonPlan
from common.contracts.lesson_sequence import (
    KnowledgeComponent,
    LessonSequence,
    PrerequisiteEdge,
    SessionPlan,
)
from common.contracts.methodology_registry import (
    METHODOLOGY_REGISTRY,
    MethodologyRegistryEntry,
    MethodologyTag,
)
from common.contracts.log_context import LogContext
from common.contracts.quality import (
    ArtifactQualityReport,
    ExportReadinessReport,
    HealingDecision,
    HealingStrategy,
    QualityFailureClass,
    QualityIssue,
)
from common.contracts.research_brief import (
    ArtifactResearchGuidance,
    EvidenceCitation,
    PrePlanningSearchBrief,
    ResearchBrief,
)
from common.contracts.research_bundle import ResearchBundle, ResearchSource
from common.contracts.roadmap import (
    RoadmapContent,
    RoadmapHero,
    RoadmapSection,
    RoadmapSidebar,
)
from common.contracts.rubric import Rubric, RubricCriterion, RubricLevel, RubricRegistry
from common.contracts.run_contract import (
    ContractRevision,
    ContractRevisionMeta,
    DecompositionIntent,
    PublishTarget,
    RunContract,
)
from common.contracts.slide_deck import (
    SlideDeckAccessibility,
    SlideDeckBlock,
    SlideDeckData,
    SlideDeckInteraction,
    SlideDeckInteractionOption,
    SlideDeckInteractionTeacherOnly,
    SlideDeckMedia,
    SlideDeckMediaPolicy,
    SlideDeckProgression,
    SlideDeckSlide,
    SlideDeckSourceRef,
    SlideDeckSurface,
    SlideDeckSurfaces,
    SlideDeckTeacherOnly,
)
from common.contracts.seam_contracts import (
    ArtifactWorkflowHandoff,
    PlannerHandoff,
    ResearcherHandoff,
)
from common.contracts.student_profile import LearningStyle, PersonalityTrait, StudentProfile
from common.contracts.student_response import StudentAnswerItem, StudentResponse
from common.contracts.unit_view import (
    UnitAggregate,
    UnitCoherenceWarning,
    UnitEventEnvelope,
    UnitParentMeta,
    UnitSessionProgress,
    UnitView,
)
from common.contracts.vocabulary_batch import (
    AnchorCard,
    AmbiguousVocabularyCluster,
    ClusterExportPolicy,
    ClusterProjectionRefs,
    InputNormalizationReport,
    LexicalExamplePair,
    LexicalGroundingCacheKeys,
    LexicalGroundingBundle,
    LexicalGroundingRequest,
    LexicalGroundingSourceEvidence,
    LexicalTermDefinition,
    LexicalUsageConstraint,
    NormalizedVocabularyCluster,
    PracticeItem,
    PracticeSet,
    SemanticAnchorCluster,
    VocabularyBatchConfig,
)
from common.contracts.vocabulary_cluster_workflow import (
    VocabularyClusterEvidenceEntry,
    VocabularyClusterWorkflow,
)

__all__ = [
    "ArtifactContent",
    "Flashcard",
    "FlashcardDeckData",
    "ArtifactGenerationInput",
    "ArtifactResearchGuidance",
    "ArtifactQualityReport",
    "ArtifactWorkflowState",
    "ArtifactStrategyProjection",
    "BloomGap",
    "ClassProfile",
    "DiagnosticReport",
    "KnowledgeGap",
    "LearningStyle",
    "MisconceptionPattern",
    "PersonalityTrait",
    "StudentAnswerItem",
    "StudentProfile",
    "StudentResponse",
    "AnswerKeyContent",
    "AnswerKeyMetadata",
    "AnswerKeySection",
    "AnchorCard",
    "AmbiguousVocabularyCluster",
    "AssessmentCheckpoint",
    "ContentComponent",
    "ComponentStrategyMode",
    "ComponentStrategyPlan",
    "ComponentStrategyRequest",
    "ComponentStrategyResult",
    "ComponentStrategyStatus",
    "ComplianceSafety",
    "ContractRevision",
    "ContractRevisionMeta",
    "ClusterExportPolicy",
    "ClusterProjectionRefs",
    "DecompositionIntent",
    "ErrorCode",
    "ErrorResponse",
    "EvidenceCitation",
    "ExportReadinessReport",
    "ExportProjectionState",
    "ExportProjectionStatus",
    "FallbackMetadata",
    "FeedbackEventType",
    "FeedbackSource",
    "HealingDecision",
    "HealingStrategy",
    "InverseThinkingCase",
    "InverseThinkingPack",
    "InverseThinkingStudentChallenge",
    "InverseThinkingSummaryRow",
    "InverseThinkingTeacherOnly",
    "InputNormalizationReport",
    "JudgeOutput",
    "KnowledgeComponent",
    "LayerScore",
    "LessonPlan",
    "LessonSequence",
    "LearningObjective",
    "LearningPreferences",
    "LexicalGroundingBundle",
    "LexicalGroundingCacheKeys",
    "LexicalGroundingRequest",
    "LexicalGroundingSourceEvidence",
    "LexicalExamplePair",
    "LexicalTermDefinition",
    "LexicalUsageConstraint",
    "LogContext",
    "METHODOLOGY_REGISTRY",
    "MethodologyRegistryEntry",
    "MethodologyTag",
    "NormalizedVocabularyCluster",
    "ObjectiveRef",
    "ObjectiveCoverage",
    "PipelineErrorResponse",
    "PrerequisiteRisk",
    "PrePlanningSearchBrief",
    "PracticeItem",
    "PracticeSet",
    "PublishTarget",
    "QualityFailureClass",
    "QualityIssue",
    "ResearchRiskLevel",
    "ResearchBrief",
    "ResearchBundle",
    "ResearchSource",
    "ResearchSignals",
    "RevisionActor",
    "RoadmapContent",
    "RoadmapHero",
    "RoadmapSection",
    "RoadmapSidebar",
    "Role",
    "Rubric",
    "RubricCriterion",
    "RubricLevel",
    "RubricRegistry",
    "RunContract",
    "SemanticAnchorCluster",
    "SourceConfidence",
    "SlideDeckAccessibility",
    "SlideDeckBlock",
    "SlideDeckData",
    "SlideDeckInteraction",
    "SlideDeckInteractionOption",
    "SlideDeckInteractionTeacherOnly",
    "SlideDeckMedia",
    "SlideDeckMediaPolicy",
    "SlideDeckProgression",
    "SlideDeckSlide",
    "SlideDeckSourceRef",
    "SlideDeckSurface",
    "SlideDeckSurfaces",
    "SlideDeckTeacherOnly",
    "PrerequisiteEdge",
    "SessionPlan",
    "StrategyBlockingIssue",
    "StrategyBlockingIssueCode",
    "StrategyDecisionLedger",
    "StrategyFeedbackEvent",
    "StrategyObservabilitySummary",
    "StrategyQualityScore",
    "StrategyRequestFingerprint",
    "StrategyRevision",
    "StrategyRevisionMateriality",
    "StrategySlot",
    "StrategySlotBudget",
    "StrategyVariant",
    "StrategyWarning",
    "StrategyWarningCode",
    "TeacherPreferenceSignals",
    "TeachingPack",
    "Token",
    "User",
    "UnitAggregate",
    "UnitCoherenceWarning",
    "UnitEventEnvelope",
    "UnitParentMeta",
    "UnitSessionProgress",
    "UnitView",
    "ValidationErrorDetail",
    "VocabularyBatchConfig",
    "VocabularyClusterEvidenceEntry",
    "VocabularyClusterWorkflow",
    "ArtifactWorkflowHandoff",
    "PlannerHandoff",
    "ResearcherHandoff",
]
