import type { RenderLocale } from "../core/types.js";

export type MessageKey =
  | "label.objectives"
  | "label.objectives.heading"
  | "label.objectives.prefix"
  | "label.grade"
  | "label.subject"
  | "label.teacher"
  | "label.student"
  | "label.print.header"
  | "label.generatedBy"
  | "label.quiz.timeLimit"
  | "label.quiz.question"
  | "label.quiz.explanation"
  | "label.lesson.summary"
  | "label.answerKey"
  | "label.answerKey.teacher";

export type Messages = Record<MessageKey, string>;

const VI_MESSAGES: Messages = {
  "label.objectives": "Mục tiêu",
  "label.objectives.heading": "Mục tiêu học kỳ",
  "label.objectives.prefix": "Học sinh sẽ có thể",
  "label.grade": "Lớp",
  "label.subject": "Môn học",
  "label.teacher": "Giáo viên",
  "label.student": "Học sinh",
  "label.print.header": "In bởi oh-my-class",
  "label.generatedBy": "Được tạo bởi oh-my-class",
  "label.quiz.timeLimit": "Thời gian",
  "label.quiz.question": "Câu",
  "label.quiz.explanation": "Giải thích",
  "label.lesson.summary": "Tóm tắt",
  "label.answerKey": "Đáp án",
  "label.answerKey.teacher": "Đáp án · Giáo viên",
};

const EN_MESSAGES: Messages = {
  "label.objectives": "Objectives",
  "label.objectives.heading": "Learning Objectives",
  "label.objectives.prefix": "Students will be able to",
  "label.grade": "Grade",
  "label.subject": "Subject",
  "label.teacher": "Teacher",
  "label.student": "Student",
  "label.print.header": "Printed by oh-my-class",
  "label.generatedBy": "Generated by oh-my-class",
  "label.quiz.timeLimit": "Time limit",
  "label.quiz.question": "Question",
  "label.quiz.explanation": "Explanation",
  "label.lesson.summary": "Summary",
  "label.answerKey": "Answer Key",
  "label.answerKey.teacher": "Answer Key · Teacher Edition",
};

const CATALOGS: Record<RenderLocale, Messages> = {
  vi: VI_MESSAGES,
  en: EN_MESSAGES,
};

export function resolveMessages(locale: RenderLocale): Messages {
  return CATALOGS[locale];
}

export function assertAllKeysPresent(messages: Messages): void {
  const allKeys: MessageKey[] = [
    "label.objectives", "label.objectives.heading", "label.objectives.prefix",
    "label.grade", "label.subject", "label.teacher", "label.student",
    "label.print.header", "label.generatedBy", "label.quiz.timeLimit",
    "label.quiz.question", "label.quiz.explanation", "label.lesson.summary",
    "label.answerKey", "label.answerKey.teacher",
  ];
  for (const key of allKeys) {
    if (!messages[key]) {
      throw new Error(`MessageCatalog is missing key: ${key}`);
    }
  }
}
